### ISSUE TITLE
Fix default file association

### ISSUE THREAD

**Issue by gertsonderby** [gertsonderby/kerbal-config#3]
File association (.cfg, .sfs and .craft) needs to be automatic.

**Comment by yalov** [comment]
config.cson
```
"*":
  core:
    customFileTypes:
      "source.ksp-cfg": [
        "cfg"
        "sfs"
        "craft"
      ]
```

**Comment by gertsonderby** [comment]
Would you be kind enough to make a pull request of this?

**Comment by yalov** [comment]
It is for user-defined config. 
I don't know where it should be in the extension file-tree
